### PR TITLE
Fix Syntax issues on various sections of the code

### PR DESCRIPTION
**Pull request by Ethanol10**
Attempting to fix some syntax issues found during compilation

### CODE REVIEW

**Comment by Ethanol10** [comment]
@Archfx should resolve all the issues found in the compiler output.

**Comment by Archfx** [comment]
Thanks

**Comment by Ethanol10** [comment]
I definitely need to get an env up to avoid having to go through compiler issues on main lol.

**Comment by Archfx** [comment]
> I definitely need to get an env up to avoid having to go through compiler issues on main lol.

Where is the problem in setting up the environment? Maybe I can help. you can use the following commands to compile the posture processor separately.

```shell
#!/bin/bash
set -e

BL=$PWD/treble_aosp
BD=$PWD/duo-de/builds
BV=$1


echo "--> Setting up build environment"
source build/envsetup.sh &>/dev/null
mkdir -p $BD
lunch treble_arm64_bgN-ap2a-userdebug
make PostureProcessor
```

**Comment by Ethanol10** [comment]
Its more so I have only messed with Windows Subsystem for Linux, and that has its own pitfalls. I do believe I just need to setup a separate disk formatted to ext4 to get it running, but I haven't had the time recently. NTFS seems to fail, as the case-insensitivity filenames are a thing in that format.

**Comment by Archfx** [comment]
> Its more so I have only messed with Windows Subsystem for Linux, and that has its own pitfalls. I do believe I just need to setup a separate disk formatted to ext4 to get it running, but I haven't had the time recently. NTFS seems to fail, as the case-insensitivity filenames are a thing in that format.

Yep, Linux is a must.

**Comment by Archfx** [comment]
I had to change `val posture:` to `var posture:` in [here](https://github.com/Archfx/duoPosture/blame/main/src/main/kotlin/com/thain/duo/PostureProcessorService.kt#L436) to accommodate your changes, build is almost complete now!

**Comment by Ethanol10** [comment]
Awesome! Sorry for the inconvenience, hope it works this time!

**Comment by Archfx** [comment]
The build is available now, you can test it and let me know.

**Comment by Ethanol10** [comment]
Im assuming this requires a wiped user data to get running, cause even in DSU it's stuck on boot.

**Comment by Archfx** [comment]
Oh no, don't proceed, the AOSP repos have updated with some settings that prevent old kernel devices from booting.  I thought this was introduced by the latest Trebledroid patches used to build the v1102 and reverted all the changes for this build. Let me check on this.

**Comment by Ethanol10** [comment]
@Archfx Looks like the feature works as expected, the device doesn't change screen and stays on the screen selected in the settings.

**Comment by Archfx** [comment]
Great! Building the vanilla image now. Everything will be available via OTA.

**Pull request merged**
